id: I20200CE6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:11:56+00:00'
last_modified: '2022-06-07T22:12:28.314038+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29035
  title: གསུང་འབུམ། རོལ་པའི་རྡོ་རྗེ། （དྷ་རམ་ས་ལ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    816E:
      image_group_id: I5031
      title: ''
      total_pages: 1160
      order: 1
      base_file: 816E.txt
    37CF:
      image_group_id: I5032
      title: ''
      total_pages: 580
      order: 2
      base_file: 37CF.txt
    5A1F:
      image_group_id: I5033
      title: ''
      total_pages: 664
      order: 3
      base_file: 5A1F.txt
    684C:
      image_group_id: I5034
      title: ''
      total_pages: 644
      order: 4
      base_file: 684C.txt
    4BFE:
      image_group_id: I5035
      title: ''
      total_pages: 636
      order: 5
      base_file: 4BFE.txt
    2EAE:
      image_group_id: I5036
      title: ''
      total_pages: 666
      order: 6
      base_file: 2EAE.txt
    E69C:
      image_group_id: I5037
      title: ''
      total_pages: 746
      order: 7
      base_file: E69C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
