id: I20200CE6
legacy_id: P004350
ocr_import_info:
  bdrc_scan_id: W29035
  source: bdrc
  ocr_info:
    timestamp: '2021-01-18T10:26:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T09:37:14.022570+00:00'
last_modified: 2022-09-02 17:42:40.915326
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29035
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29035
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། རོལ་པའི་རྡོ་རྗེ། （དྷ་རམ་ས་ལ།）
  author: ལྕང་སྐྱ་རོལ་པའི་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7157095537262451
  ocr_word_median_confidence_index: 0.77
quality: null
bases:
  I5033:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5033
      total_pages: 664
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I5033.txt
    statistics:
      ocr_word_median_confidence_index: 0.72
      ocr_word_mean_confidence_index: 0.6669494039089815
    legacy_id: v003
  I5032:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5032
      total_pages: 580
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5032.txt
    statistics:
      ocr_word_median_confidence_index: 0.8
      ocr_word_mean_confidence_index: 0.7373069795148426
    legacy_id: v002
  I5036:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5036
      total_pages: 666
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I5036.txt
    statistics:
      ocr_word_median_confidence_index: 0.77
      ocr_word_mean_confidence_index: 0.7160754875114698
    legacy_id: v006
  I5034:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5034
      total_pages: 644
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I5034.txt
    statistics:
      ocr_word_median_confidence_index: 0.79
      ocr_word_mean_confidence_index: 0.7208064144933674
    legacy_id: v004
  I5035:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5035
      total_pages: 636
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I5035.txt
    statistics:
      ocr_word_median_confidence_index: 0.78
      ocr_word_mean_confidence_index: 0.7189272497967176
    legacy_id: v005
  I5037:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5037
      total_pages: 746
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I5037.txt
    statistics:
      ocr_word_median_confidence_index: 0.81
      ocr_word_mean_confidence_index: 0.7466778474194496
    legacy_id: v007
  I5031:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5031
      total_pages: 1160
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5031.txt
    statistics:
      ocr_word_median_confidence_index: 0.76
      ocr_word_mean_confidence_index: 0.7105496811710225
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
