id: P004350
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W29035
  title: གསུང་འབུམ། རོལ་པའི་རྡོ་རྗེ། （དྷ་རམ་ས་ལ།）
  author: ''
  volumes:
    871634f3159a4f0e8191c1deb3a16005:
      image_group_id: I5031
      title: ''
      volume_number: 1
      total_pages: 1160
      base_file: v001.txt
    8f442c54548244e088abe3dfb0da34d0:
      image_group_id: I5032
      title: ''
      volume_number: 2
      total_pages: 580
      base_file: v002.txt
    2ac2ad9d1a75469e8e335d9699165eb7:
      image_group_id: I5033
      title: ''
      volume_number: 3
      total_pages: 664
      base_file: v003.txt
    95f3034a80f845af9f456fa0ca5abf70:
      image_group_id: I5034
      title: ''
      volume_number: 4
      total_pages: 644
      base_file: v004.txt
    ed5eaf8a66bf40979421918c986674d9:
      image_group_id: I5035
      title: ''
      volume_number: 5
      total_pages: 636
      base_file: v005.txt
    fc5f289d9cc24f49921c5d24216cf1c0:
      image_group_id: I5036
      title: ''
      volume_number: 6
      total_pages: 666
      base_file: v006.txt
    29badd65193a4258b28055f425aa4b34:
      image_group_id: I5037
      title: ''
      volume_number: 7
      total_pages: 746
      base_file: v007.txt
    c06fd97576d049e5bf18a26e6c2d168e:
      image_group_id: I5038
      title: ''
      volume_number: 8
      total_pages: 0
